openapi: 3.0.0
info:
  description: Pipeline v0.3.0 swagger
  version: "0.3.0"
  title: Pipeline API
  contact:
    email: info@banzaicloud.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: cluster
    description: Cluster realted funtions
  - name: clusters
    description: Clusters realted funtions
paths:
  /clusters:
    post:
      security:
        - bearerAuth: []
      tags:
        - clusters
      summary: Create cluster
      description: Create a new K8S cluster in the cloud
      operationId: CreateCluster
      responses:
        '200':
          description: Cluster created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateClusterResponse_200'
        '400':
          description: Cluster creation failed
          content:
            application/json:
             schema:
                $ref: '#/components/schemas/CreateClusterResponse_400'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateClusterRequest'

            examples:
              AWS:
                value:
                  name: "awscluster-pipelineuser-123"
                  location: "eu-west-1"
                  cloud: "amazon"
                  nodeInstanceType: "m4.xlarge"
                  properties:
                    properties:
                      amazon:
                        $ref: '#components/schemas/CreateAmazonProperties'

              AKS:
                value:
                  name: "azcluster-pipelineuser-123"
                  location: "westeurope"
                  cloud: "azure"
                  nodeInstanceType: "Standard_D2_v2"
                  properties:
                    azure:
                      $ref: '#components/schemas/CreateAzureProperties'

              GKE:
                value:
                  name: "gkecluster-pipelineuser-123"
                  location: "us-central1-a"
                  cloud: "google"
                  nodeInstanceType: "n1-standard-1"
                  properties:
                    google:
                      $ref: '#components/schemas/CreateGoogleProperties'
    get:
      security:
        - bearerAuth: []
      tags:
        - clusters
      summary: List clusters
      operationId: ListClusters
      description: Listing all the K8S clusters from the cloud
      responses:
        '200':
          description: All cluster listed
          content:
            application/json:
             schema:
                $ref: '#/components/schemas/ClusterListResponse'
        '400':
          description: Error during listing clusters
          content:
            application/json:
             schema:
                $ref: '#/components/schemas/BaseError_400'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
  '/clusters/{id}':
    get:
      security:
        - bearerAuth: []
      tags:
        - cluster
      summary: Get cluster
      description: Getting cluster details
      operationId: GetCluster
      parameters:
        - name: id
          in: path
          description: Selected cluster identification (number)
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Getting cluster succeeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateClusterResponse_200'
        '400':
          description: Error during getting cluster details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError_400'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '404':
          description: Cluster not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClusterNotFound'

    put:
      security:
        - bearerAuth: []
      tags:
        - cluster
      summary: Update cluster
      description: Updating an existing K8S cluster
      operationId: UpdateCluster
      parameters:
        - name: id
          in: path
          description: Selected cluster identification (number)
          required: true
          schema:
            type: integer
      responses:
        '202':
          description: Cluster update accepted
        '400':
          description: Error during updating cluster
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError_400'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '404':
          description: Cluster not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClusterNotFound'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateClusterRequest'
            examples:
              AWS:
                value:
                  cloud: "amazon"
                  properties:
                    properties:
                      amazon:
                        $ref: '#components/schemas/CreateAmazonProperties'

              AKS:
                value:
                  cloud: "azure"
                  properties:
                    azure:
                      $ref: '#components/schemas/CreateAzureProperties'

              GKE:
                value:
                  cloud: "google"
                  properties:
                    google:
                      $ref: '#components/schemas/CreateGoogleProperties'
    delete:
      security:
        - bearerAuth: []
      tags:
        - cluster
      summary: Delete cluster
      description: Deleting a K8S cluster
      operationId: DeleteCluster
      parameters:
        - name: id
          in: path
          description: Selected cluster identification (number)
          required: true
          schema:
            type: integer
      responses:
        '202':
          description: Cluster deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClusterDelete_200'
        '400':
          description: Error during deleting cluster
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError_400'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '404':
          description: Cluster not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClusterNotFound'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT


  schemas:

    CreateClusterRequest:
      type: object
      required:
        - name
        - location
        - nodeInstanceType
        - cloud
        - properties
      properties:
        name:
          type: string
          example: "gkecluster-pipelineuser-123"
        location:
          type: string
          example: "us-central1-a"
        nodeInstanceType:
          type: string
          example: "n1-standard-1"
        cloud:
          type: string
          example: "google"
        properties:
          type: object

    CreateAmazonProperties:
      type: object
      required:
        - master
        - node
      properties:
        master:
          type: object
          properties:
            instanceType:
              type: string
            image:
              type: string
        node:
          type: object
          properties:
            spotPrice:
              type: string
            minCount:
              type: integer
            maxCount:
              type: integer
            image:
              type: string
    CreateAzureProperties:
      type: object
      required:
        - node
      properties:
        node:
          type: object
          required:
            - resourceGroup
          properties:
            resourceGroup:
              type: string
            agentCount:
              type: integer
            agentName:
              type: string
            kubernetesVersion:
              type: string

    CreateGoogleProperties:
      type: object
      required:
         - project
      properties:
        project:
          type: string
        master:
          type: object
          properties:
            version:
              type: string
        node:
          type: object
          properties:
            count:
              type: string
            version:
              type: string
            serviceAccount:
              type: string

    CreateClusterResponse_200:
      type: object
      properties:
        status:
          type: integer
          example: 200
        name:
          type: string
          example: "gkecluster-pipelineuser-123"
        location:
          type: string
          example: "us-central1-a"
        cloud:
          type: string
          example: "google"
        nodeInstanceType:
          type: string
          example: "n1-standard-1"
        id:
          type: integer
          example: 1

    CreateClusterResponse_400:
      type: object
      properties:
        code:
          type: integer
          example: 400
        message:
          type: string
          example: Invalid version
        error:
          type: string
          example: Invalid version

    ClusterListResponse:
      type: array
      items:
        $ref: '#components/schemas/CreateClusterResponse_200'

    BaseError_400:
      type: object
      properties:
        code:
          type: integer
          example: 400
        message:
          type: string
          example: "Error during process"
        error:
          type: string
          example: "Error during process"

    ClusterNotFound:
      type: object
      properties:
        code:
          type: integer
          example: 404
        message:
          type: string
          example: "Cluster not found"
        error:
          type: string
          example: "record not found"

    UpdateClusterRequest:
      type: object
      required:
        - cloud
        - properties
      properties:
        cloud:
          type: string
        properties:
          type: object

    UpdateAmazonProperties:
      type: object
      properties:
        node:
          type: object
          properties:
            minCount:
              type: integer
              example: 2
            maxCount:
              type: integer
              example: 4

    UpdateAzureProperties:
      type: object
      properties:
        node:
          type: object
          properties:
            agentCount:
              type: integer
              example: 2

    UpdateGoogleProperties:
      type: object
      properties:
        master:
          type: object
          properties:
            version:
              type: string
        node:
          type: object
          properties:
            count:
              type: string
            version:
              type: string
            serviceAccount:
              type: string

    ClusterDelete_200:
      type: object
      properties:
        status:
          type: integer
          example: 202
        name:
          type: string
          example: "gkecluster-pipelineuser-123"
        message:
          type: string
          example: "Cluster deleted successfully"
        id:
          type: integer
          example: 1

    Unauthorized:
      type: object
      properties:
        code:
          type: integer
          example: 401
        message:
          type: string
          example: "Invalid token"
        error:
          type: string
          example: "token contains an invalid number of segments"




